security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        jwt_user_provider:
            id: App\Identity\Infrastructure\Security\JwtUserProvider

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        login:
            pattern: ^/api/v1/auth/login
            stateless: true
            security: false

        refresh:
            pattern: ^/api/v1/auth/refresh
            stateless: true
            security: false

        api:
            pattern: ^/api
            stateless: true
            custom_authenticators:
                - App\Identity\Infrastructure\Security\JwtAuthenticator

    access_control:
        - { path: ^/api/v1/payments/webhook, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/auth, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1, roles: PUBLIC_ACCESS }
